services:
  - type: web
    name: employee-salary-management-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: RAILS_ENV
        value: production
